import images from '@/constants/image';

export type LeadType = 'person' | 'company';

export interface Lead {
    id: number;
    type: LeadType;
    logo: string;
    name: string;
    companyName?: string;
    position?: string;
    bio: string;
    email: string;
    phone: string;
    location: string;
    experience: string;
    industry: string;
    interest: string;
    // Extended profile fields
    companyStage?: string;
    keyStrength?: string;
    topGoal?: string;
    baseLocation?: string;
    operatesIn?: string;
    memberSince?: string;
    responseRate?: string;
    successfulDealsRate?: string;
    rating?: number;
    // New Lead Bank profile fields
    linkedin?: string;
    twitter?: string;
    facebook?: string;
    instagram?: string;
    address?: string;
    companyDescription?: string;
}

export const leads: Lead[] = [
    {
        id: 1,
        type: 'person',
        logo: images.userCheckleads,
        name: 'Thabo Ladi',
        position: 'COO EasyAccount',
        bio: 'Seasoned renewable energy executive with 8 years of experience building solar infrastructure across East and West Africa.',
        email: 'thabo@gmail.com',
        phone: '+234 803 040 200',
        location: 'Nigeria',
        experience: '8 years',
        industry: 'Fintech',
        interest: 'Strategy & Finance',
        companyStage: 'Growth Stage',
        keyStrength: 'Strategic Leadership',
        topGoal: 'Scale renewable energy projects across Africa',
        baseLocation: 'Lagos',
        operatesIn: 'Nigeria, Ghana, Kenya',
        memberSince: '2021-03-15',
        responseRate: '95%',
        successfulDealsRate: '88%',
        rating: 4.7,
    },
    {
        id: 2,
        type: 'person',
        logo: images.userCheckleads,
        name: 'Aisha Bello',
        position: 'Product Manager',
        bio: 'Product leader focused on fintech platforms and user-centric financial solutions.',
        email: 'aisha@gmail.com',
        phone: '+234 701 223 110',
        location: 'Lagos, Nigeria',
        experience: '6 years',
        industry: 'Fintech',
        interest: 'Product Strategy',
        companyStage: 'Series A',
        keyStrength: 'User Research',
        topGoal: 'Launch mobile-first financial products',
        baseLocation: 'Lagos',
        operatesIn: 'Nigeria',
        memberSince: '2022-07-20',
        responseRate: '92%',
        successfulDealsRate: '85%',
        rating: 4.5,
    },
    {
        id: 3,
        type: 'person',
        logo: images.userCheckleads,
        name: 'Michael Okoye',
        position: 'CTO',
        bio: 'Engineering executive leading scalable cloud and AI-driven platforms.',
        email: 'michael@techmail.com',
        phone: '+234 809 555 332',
        location: 'Abuja, Nigeria',
        experience: '10 years',
        industry: 'Technology',
        interest: 'AI & Cloud',
        companyStage: 'Series B',
        keyStrength: 'Technical Architecture',
        topGoal: 'Build AI-powered enterprise solutions',
        baseLocation: 'Abuja',
        operatesIn: 'Africa, Europe',
        memberSince: '2020-01-10',
        responseRate: '89%',
        successfulDealsRate: '92%',
        rating: 4.9,
    },
    {
        id: 4,
        type: 'person',
        logo: images.userCheckleads,
        name: 'Sarah Mensah',
        position: 'Investment Analyst',
        bio: 'Private equity analyst with strong focus on African startups.',
        email: 'sarah@invest.com',
        phone: '+233 501 778 900',
        location: 'Accra, Ghana',
        experience: '5 years',
        industry: 'Investment',
        interest: 'Venture Capital',
        companyStage: 'Established',
        keyStrength: 'Financial Analysis',
        topGoal: 'Identify high-growth African startups',
        baseLocation: 'Accra',
        operatesIn: 'Ghana, Nigeria, Kenya',
        memberSince: '2023-02-28',
        responseRate: '87%',
        successfulDealsRate: '78%',
        rating: 4.3,
    },
    {
        id: 5,
        type: 'person',
        logo: images.userCheckleads,
        name: 'Daniel Ade',
        position: 'Growth Lead',
        bio: 'Growth strategist driving user acquisition and partnerships.',
        email: 'daniel@growth.io',
        phone: '+234 812 665 778',
        location: 'Ibadan, Nigeria',
        experience: '7 years',
        industry: 'Marketing',
        interest: 'Growth & Partnerships',
        companyStage: 'Growth Stage',
        keyStrength: 'Partnership Development',
        topGoal: 'Triple user base in 12 months',
        baseLocation: 'Ibadan',
        operatesIn: 'Nigeria',
        memberSince: '2021-09-05',
        responseRate: '94%',
        successfulDealsRate: '90%',
        rating: 4.6,
    },
    {
        id: 6,
        type: 'person',
        logo: images.userCheckleads,
        name: 'Fatima Yusuf',
        position: 'Operations Manager',
        bio: 'Operations expert optimizing business workflows and performance.',
        email: 'fatima@ops.com',
        phone: '+234 805 112 889',
        location: 'Ilorin, Nigeria',
        experience: '6 years',
        industry: 'Operations',
        interest: 'Process Optimization',
        companyStage: 'Seed Stage',
        keyStrength: 'Workflow Automation',
        topGoal: 'Reduce operational costs by 30%',
        baseLocation: 'Ilorin',
        operatesIn: 'Nigeria',
        memberSince: '2022-11-12',
        responseRate: '91%',
        successfulDealsRate: '82%',
        rating: 4.4,
    },
    {
        id: 7,
        type: 'person',
        logo: images.userCheckleads,
        name: 'Joseph Kamau',
        position: 'Business Development Lead',
        bio: 'Building strategic partnerships across East Africa.',
        email: 'joseph@bd.com',
        phone: '+254 722 123 456',
        location: 'Nairobi, Kenya',
        experience: '9 years',
        industry: 'Business Development',
        interest: 'Strategic Alliances',
        companyStage: 'Series A',
        keyStrength: 'Relationship Building',
        topGoal: 'Expand into 5 new East African markets',
        baseLocation: 'Nairobi',
        operatesIn: 'Kenya, Uganda, Tanzania, Rwanda',
        memberSince: '2020-06-18',
        responseRate: '96%',
        successfulDealsRate: '91%',
        rating: 4.8,
    },
    {
        id: 8,
        type: 'person',
        logo: images.userCheckleads,
        name: 'Linda Adebayo',
        position: 'UX Researcher',
        bio: 'User research specialist improving digital product usability.',
        email: 'linda@uxmail.com',
        phone: '+234 810 456 221',
        location: 'Lagos, Nigeria',
        experience: '4 years',
        industry: 'Design',
        interest: 'UX Research',
        companyStage: 'Pre-Seed',
        keyStrength: 'User Interviews',
        topGoal: 'Improve product NPS by 25 points',
        baseLocation: 'Lagos',
        operatesIn: 'Nigeria',
        memberSince: '2023-04-22',
        responseRate: '88%',
        successfulDealsRate: '75%',
        rating: 4.2,
    },
    {
        id: 9,
        type: 'person',
        logo: images.userCheckleads,
        name: 'Peter Johnson',
        position: 'Financial Consultant',
        bio: 'Advising startups on finance, compliance, and scaling.',
        email: 'peter@finance.com',
        phone: '+1 415 667 8899',
        location: 'San Francisco, USA',
        experience: '12 years',
        industry: 'Finance',
        interest: 'Startup Advisory',
        companyStage: 'Established',
        keyStrength: 'Financial Modeling',
        topGoal: 'Help 50 startups raise Series A',
        baseLocation: 'San Francisco',
        operatesIn: 'USA, Africa, Europe',
        memberSince: '2019-08-14',
        responseRate: '85%',
        successfulDealsRate: '94%',
        rating: 4.9,
    },
    {
        id: 10,
        type: 'person',
        logo: images.userCheckleads,
        name: 'Amaka Nwoye',
        position: 'HR Business Partner',
        bio: 'Talent and culture strategist for fast-growing teams.',
        email: 'amaka@hrpro.com',
        phone: '+234 907 334 889',
        location: 'Enugu, Nigeria',
        experience: '8 years',
        industry: 'Human Resources',
        interest: 'Talent Management',
        companyStage: 'Growth Stage',
        keyStrength: 'Talent Acquisition',
        topGoal: 'Build high-performing remote teams',
        baseLocation: 'Enugu',
        operatesIn: 'Nigeria',
        memberSince: '2021-12-01',
        responseRate: '93%',
        successfulDealsRate: '86%',
        rating: 4.5,
    },

    {
        id: 11,
        type: 'company',
        logo: images.buildingleads,
        name: 'P23 Africa',
        companyName: 'P23 Africa',
        bio: 'Fast growing African fintech company scaling SME financial products.',
        email: 'info@p23africa.com',
        phone: '+234 800 000 000',
        location: 'Africa',
        experience: '5 years',
        industry: 'Business & Tech',
        interest: 'Payments',
        companyStage: 'Series B',
        keyStrength: 'Pan-African Network',
        topGoal: 'Become the leading SME fintech in Africa',
        baseLocation: 'Lagos',
        operatesIn: 'Nigeria, Ghana, Kenya, South Africa',
        memberSince: '2019-05-10',
        responseRate: '97%',
        successfulDealsRate: '93%',
        rating: 4.9,
    },
    {
        id: 12,
        type: 'company',
        logo: images.buildingleads,
        name: 'GreenEnergy Africa',
        companyName: 'GreenEnergy Africa',
        bio: 'Renewable energy company providing solar infrastructure.',
        email: 'contact@greenenergy.africa',
        phone: '+234 900 111 222',
        location: 'Nigeria',
        experience: '7 years',
        industry: 'Energy',
        interest: 'Renewables',
        companyStage: 'Series A',
        keyStrength: 'Solar Installation',
        topGoal: 'Power 1 million homes with solar',
        baseLocation: 'Lagos',
        operatesIn: 'Nigeria, Ghana',
        memberSince: '2020-02-14',
        responseRate: '89%',
        successfulDealsRate: '85%',
        rating: 4.6,
    },
    {
        id: 13,
        type: 'company',
        logo: images.buildingleads,
        name: 'PayWave',
        companyName: 'PayWave',
        bio: 'Digital payments infrastructure for African businesses.',
        email: 'hello@paywave.io',
        phone: '+254 700 445 889',
        location: 'Kenya',
        experience: '6 years',
        industry: 'Fintech',
        interest: 'Payments',
        companyStage: 'Growth Stage',
        keyStrength: 'API Integration',
        topGoal: 'Process $1B in transactions annually',
        baseLocation: 'Nairobi',
        operatesIn: 'Kenya, Uganda, Tanzania',
        memberSince: '2020-08-22',
        responseRate: '94%',
        successfulDealsRate: '91%',
        rating: 4.7,
    },
    {
        id: 14,
        type: 'company',
        logo: images.buildingleads,
        name: 'AgroLink',
        companyName: 'AgroLink',
        bio: 'Connecting farmers to markets through technology.',
        email: 'info@agrolink.com',
        phone: '+233 550 778 112',
        location: 'Ghana',
        experience: '4 years',
        industry: 'AgriTech',
        interest: 'Food Supply Chain',
        companyStage: 'Seed Stage',
        keyStrength: 'Farmer Network',
        topGoal: 'Onboard 100,000 farmers',
        baseLocation: 'Accra',
        operatesIn: 'Ghana, Ivory Coast',
        memberSince: '2022-01-05',
        responseRate: '86%',
        successfulDealsRate: '78%',
        rating: 4.3,
    },
    {
        id: 15,
        type: 'company',
        logo: images.buildingleads,
        name: 'CloudNova',
        companyName: 'CloudNova',
        bio: 'Cloud solutions provider for enterprises and startups.',
        email: 'support@cloudnova.io',
        phone: '+1 408 992 2211',
        location: 'USA',
        experience: '8 years',
        industry: 'Technology',
        interest: 'Cloud Infrastructure',
        companyStage: 'Established',
        keyStrength: 'Enterprise Solutions',
        topGoal: 'Expand into emerging markets',
        baseLocation: 'Silicon Valley',
        operatesIn: 'USA, Europe, Africa',
        memberSince: '2018-11-30',
        responseRate: '92%',
        successfulDealsRate: '95%',
        rating: 4.8,
    },
    {
        id: 16,
        type: 'company',
        logo: images.buildingleads,
        name: 'HealthBridge',
        companyName: 'HealthBridge',
        bio: 'Digital health platform connecting patients and providers.',
        email: 'contact@healthbridge.com',
        phone: '+234 814 555 443',
        location: 'Nigeria',
        experience: '5 years',
        industry: 'HealthTech',
        interest: 'Digital Health',
        companyStage: 'Series A',
        keyStrength: 'Telemedicine',
        topGoal: 'Reach 5 million patients',
        baseLocation: 'Lagos',
        operatesIn: 'Nigeria',
        memberSince: '2021-04-18',
        responseRate: '90%',
        successfulDealsRate: '82%',
        rating: 4.5,
    },
    {
        id: 17,
        type: 'company',
        logo: images.buildingleads,
        name: 'EduSmart',
        companyName: 'EduSmart',
        bio: 'Online education platform focused on upskilling.',
        email: 'hello@edusmart.io',
        phone: '+234 901 889 334',
        location: 'Nigeria',
        experience: '3 years',
        industry: 'EdTech',
        interest: 'Online Learning',
        companyStage: 'Pre-Seed',
        keyStrength: 'Course Content',
        topGoal: 'Train 500,000 professionals',
        baseLocation: 'Lagos',
        operatesIn: 'Nigeria, Kenya',
        memberSince: '2023-03-08',
        responseRate: '88%',
        successfulDealsRate: '76%',
        rating: 4.2,
    },
    {
        id: 18,
        type: 'company',
        logo: images.buildingleads,
        name: 'LogiFlow',
        companyName: 'LogiFlow',
        bio: 'Logistics optimization and supply chain analytics.',
        email: 'info@logiflow.com',
        phone: '+27 711 223 889',
        location: 'South Africa',
        experience: '6 years',
        industry: 'Logistics',
        interest: 'Supply Chain',
        companyStage: 'Growth Stage',
        keyStrength: 'Route Optimization',
        topGoal: 'Reduce delivery times by 40%',
        baseLocation: 'Johannesburg',
        operatesIn: 'South Africa, Botswana, Namibia',
        memberSince: '2020-10-12',
        responseRate: '91%',
        successfulDealsRate: '87%',
        rating: 4.6,
    },
    {
        id: 19,
        type: 'company',
        logo: images.buildingleads,
        name: 'SecurePay',
        companyName: 'SecurePay',
        bio: 'Secure payment gateway for global merchants.',
        email: 'support@securepay.com',
        phone: '+44 7700 900123',
        location: 'United Kingdom',
        experience: '9 years',
        industry: 'Fintech',
        interest: 'Payment Security',
        companyStage: 'Established',
        keyStrength: 'Fraud Prevention',
        topGoal: 'Achieve 99.99% uptime',
        baseLocation: 'London',
        operatesIn: 'UK, Europe, Africa',
        memberSince: '2017-07-25',
        responseRate: '95%',
        successfulDealsRate: '96%',
        rating: 4.9,
    },
    {
        id: 20,
        type: 'company',
        logo: images.buildingleads,
        name: 'BuildRight',
        companyName: 'BuildRight',
        bio: 'Construction technology company improving project delivery.',
        email: 'contact@buildright.com',
        phone: '+234 806 112 778',
        location: 'Nigeria',
        experience: '10 years',
        industry: 'Construction Tech',
        interest: 'Infrastructure',
        companyStage: 'Series B',
        keyStrength: 'Project Management',
        topGoal: 'Digitize construction across Africa',
        baseLocation: 'Abuja',
        operatesIn: 'Nigeria',
        memberSince: '2016-09-14',
        responseRate: '87%',
        successfulDealsRate: '89%',
        rating: 4.7,
    },
];
